### ISSUE TITLE
并行网关时，高亮（绿色）流程线数量不全

### ISSUE THREAD

**Issue by sxf1234** [Tezzxamo/activitiDemo#2]
debug了一下，发现原理是
1.先获得所有活动的节点（包括完成和未完成的节点）的"流入的线"
2.获得所有“起点是完成节点，终点是未完成节点的线”，并且默认未完成节点只有一条流入的线。
3.第二步的线描成红色，第一步的其余的线描成绿色。

这样有个问题就是并行网关的流入的线不止一条，就会导致“没有完成的并行网关”的入线只有一条会成为红色，其他入线都是绿色。
我的解决方法：
  将第二步的操作改成获得所有“活动的未完成节点”的入线，而不是原来的找所谓的“出线”

    //需要描成绿色的线
    public List<String> getRunningActivityFlowIdsByIcommingFlows(BpmnModel bpmnModel, List<String> runningActivityIdList, List<HistoricActivityInstance> historicActivityInstanceList){
        List<String> runningActivityFlowsIds = new ArrayList<>();
        List<String> runningActivityIds = new ArrayList<>(runningActivityIdList);
        // 逆序寻找，因为historicActivityInstanceList有序
        if (CollectionUtils.isEmpty(runningActivityIds)) {
            return runningActivityFlowsIds;
        }

        // 全部活动节点(包括正在执行的和未执行的)
        List<FlowNode> allHistoricActivityNodeList = new ArrayList<>();

        for (HistoricActivityInstance historicActivityInstance : historicActivityInstanceList) {
            // 获取流程节点
            // bpmnModel.getMainProcess()获取一个Process对象
            FlowNode flowNode = (FlowNode) bpmnModel.getMainProcess().getFlowElement(historicActivityInstance.getActivityId(), true);
            allHistoricActivityNodeList.add(flowNode);
        }

        for (int i = historicActivityInstanceList.size() - 1; i >= 0; i--) {
            HistoricActivityInstance historicActivityInstance = historicActivityInstanceList.get(i);
            FlowNode flowNode = (FlowNode) bpmnModel.getMainProcess().getFlowElement(historicActivityInstance.getActivityId(), true);
            // 如果当前节点是未完成的节点
            if (runningActivityIds.contains(flowNode.getId())) {
                // 获取每个活动节点的输入线
                List<SequenceFlow> incomingFlows = flowNode.getIncomingFlows();

                // 循环输入线，如果输入线的源头处于全部活动节点中，则将其包含在内
                for (SequenceFlow sequenceFlow : incomingFlows) {
                    if (allHistoricActivityNodeList.stream().map(BaseElement::getId).collect(Collectors.toList()).contains(sequenceFlow.getSourceFlowElement().getId())){
                        runningActivityFlowsIds.add(sequenceFlow.getId());
                    }
                }
            }

        }
        return runningActivityFlowsIds;
    }

**Comment by Tezzxamo** [comment]
收到，已经收入。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tezzxamo/activitiDemo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月12日(星期一) 下午3:10
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Tezzxamo/activitiDemo] 并行网关时，高亮（绿色）流程线数量不全 (#2)





 
debug了一下，发现原理是
 1.先获得所有活动的节点（包括完成和未完成的节点）的"流入的线"
 2.获得所有“起点是完成节点，终点是未完成节点的线”，并且默认未完成节点只有一条流入的线。
 3.第二步的线描成红色，第一步的其余的线描成绿色。
 
这样有个问题就是并行网关的流入的线不止一条，就会导致“没有完成的并行网关”的入线只有一条会成为红色，其他入线都是绿色。
 我的解决方法：
 将第二步的操作改成获得所有“活动的未完成节点”的入线，而不是原来的找所谓的“出线”
 //需要描成绿色的线 public List<String&gt; getRunningActivityFlowIdsByIcommingFlows(BpmnModel bpmnModel, List<String&gt; runningActivityIdList, List<HistoricActivityInstance&gt; historicActivityInstanceList){     List<String&gt; runningActivityFlowsIds = new ArrayList<&gt;();     List<String&gt; runningActivityIds = new ArrayList<&gt;(runningActivityIdList);     // 逆序寻找，因为historicActivityInstanceList有序     if (CollectionUtils.isEmpty(runningActivityIds)) {         return runningActivityFlowsIds;     }     // 全部活动节点(包括正在执行的和未执行的)     List<FlowNode&gt; allHistoricActivityNodeList = new ArrayList<&gt;();     for (HistoricActivityInstance historicActivityInstance : historicActivityInstanceList) {         // 获取流程节点         // bpmnModel.getMainProcess()获取一个Process对象         FlowNode flowNode = (FlowNode) bpmnModel.getMainProcess().getFlowElement(historicActivityInstance.getActivityId(), true);         allHistoricActivityNodeList.add(flowNode);     }     for (int i = historicActivityInstanceList.size() - 1; i &gt;= 0; i--) {         HistoricActivityInstance historicActivityInstance = historicActivityInstanceList.get(i);         FlowNode flowNode = (FlowNode) bpmnModel.getMainProcess().getFlowElement(historicActivityInstance.getActivityId(), true);         // 如果当前节点是未完成的节点         if (runningActivityIds.contains(flowNode.getId())) {             // 获取每个活动节点的输入线             List<SequenceFlow&gt; incomingFlows = flowNode.getIncomingFlows();             // 循环输入线，如果输入线的源头处于全部活动节点中，则将其包含在内             for (SequenceFlow sequenceFlow : incomingFlows) {                 if (allHistoricActivityNodeList.stream().map(BaseElement::getId).collect(Collectors.toList()).contains(sequenceFlow.getSourceFlowElement().getId())){                     runningActivityFlowsIds.add(sequenceFlow.getId());                 }             }         }     }     return runningActivityFlowsIds; }
